/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmdetection_free: (a: number, b: number) => void;
export const __wbg_wasmmidstream_free: (a: number, b: number) => void;
export const __wbg_wasmstreamproxy_free: (a: number, b: number) => void;
export const __wbg_wasmwatermarker_free: (a: number, b: number) => void;
export const detect: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => number;
export const detect_exact: (a: number, b: number, c: number, d: number, e: number) => number;
export const detect_selfsync: (a: number, b: number, c: number, d: number, e: number) => number;
export const wasmdetection_log10_p: (a: number) => number;
export const wasmdetection_p_value: (a: number) => number;
export const wasmdetection_scored_positions: (a: number) => number;
export const wasmdetection_z_score: (a: number) => number;
export const wasmmidstream_ack: (a: number, b: number) => void;
export const wasmmidstream_backpressure: (a: number) => number;
export const wasmmidstream_last_novel: (a: number) => number;
export const wasmmidstream_log10_p: (a: number) => number;
export const wasmmidstream_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => number;
export const wasmmidstream_novelty_ratio: (a: number) => number;
export const wasmmidstream_push_logits: (a: number, b: number, c: number) => number;
export const wasmmidstream_push_topk: (a: number, b: number, c: number, d: number, e: number) => number;
export const wasmmidstream_scored: (a: number) => number;
export const wasmmidstream_z_score: (a: number) => number;
export const wasmstreamproxy_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => number;
export const wasmstreamproxy_push_logits: (a: number, b: number, c: number) => number;
export const wasmstreamproxy_push_topk: (a: number, b: number, c: number, d: number, e: number) => number;
export const wasmstreamproxy_steps: (a: number) => number;
export const wasmwatermarker_new: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
export const wasmwatermarker_step: (a: number, b: number, c: number, d: number, e: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_start: () => void;
